lbattachment/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url('^upload__/$', views.upload__, name='lbattachment_upload__'),
    url('^delete__/$', views.delete__, name='lbattachment_delete__'),
    url('^change_descn__/$', views.change_descn__, name='lbattachment_change_descn__'),
    url('^download/$', views.download, name='lbattachment_download'),
]

likes/urls.py
#coding:utf-8

"""
    likes app
"""
from django.conf.urls import include, url
from likes.views import *
#http://localhost:8000/likes/ + 
#在project的urls.py导入整个url配置
urlpatterns = [
    url(r'^likes_change$',likes_change,name='likes_change'),
    url(r'^likes_nums$',likes_nums,name='likes_nums'),
]

ourforum/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from rest_framework import routers

from ourforum import views, profileviews
from ourforum import api
from ourforum.views import *
router = routers.DefaultRouter()
router.register(r'topic', api.TopicViewSet)

forum_patterns = [
    url(r'^(?P<forum_slug>[\w-]+)/$', views.forum, name='lbforum_forum'),
    url(r'^(?P<forum_slug>[\w-]+)/(?P<topic_type>[\w-]+)/$',
        views.forum, name='lbforum_forum'),
    url(r'^(?P<forum_slug>[\w-]+)/(?P<topic_type>[\w-]+)/(?P<topic_type2>[\w-]+)/$',
        views.forum, name='lbforum_forum'),
]

topic_patterns = [
    url('^(?P<topic_id>\d+)/$', views.topic, name='lbforum_topic'),
    url('^(?P<topic_id>\d+)/delete/$', views.delete_topic,
        name='lbforum_delete_topic'),
    url('^(?P<topic_id>\d+)/toggle_topic_attr/(?P<attr>[\w-]+)/$',
        views.toggle_topic_attr,
        name='lbforum_toggle_topic_attr'),
    url('^new/$', views.new_post, name='lbforum_new_topic'),
    url('^new/(?P<forum_id>\d+)/$', views.new_post, name='lbforum_new_topic'),
]

post_patterns = [
    url('^(?P<post_id>\d+)/$', views.post, name='lbforum_post'),
    url('^(?P<post_id>\d+)/edit/$', views.edit_post, name='lbforum_post_edit'),
    url('^(?P<post_id>\d+)/delete/$', views.delete_post,
        name='lbforum_post_delete'),
]

profile_patterns = [
    url(r'^$', profileviews.profile,
        name='lbforum_profile'),
    url(r'^(?P<user_id>\d+)/$', profileviews.profile,
        name='lbforum_profile'),
    url('^(?P<user_id>\d+)/topics/$', profileviews.user_topics,
        name='lbforum_user_topics'),
    url('^(?P<user_id>\d+)/posts/$', profileviews.user_posts,
        name='lbforum_user_posts'),
    url(r'^change/$', profileviews.change_profile,
        name='lbforum_change_profile'),
]

urlpatterns = [
    url(r'^$', views.index, name='lbforum_index'),
    url(r'^recent/$', views.recent, name='lbforum_recent'),
    url(r'^forum/', include(forum_patterns)),
    url(r'^topic/', include(topic_patterns)),
    url(r'^profile/', include(profile_patterns)),
    url(r'^api/', include(router.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^i18n/setlang', views.set_language,name='selected_language'),
    url('^reply/new/(?P<topic_id>\d+)/$', views.new_post,
        name='lbforum_new_replay'),
    url(r'^post/', include(post_patterns)),
    url(r'^lang.js$', TemplateView.as_view(template_name='ourforum/lang.js'),
        name='lbforum_lang_js'),
    url('^markitup_preview/$', views.markitup_preview,
        name='markitup_preview'),
    url(r'^makefriend/(?P<sender>\w+)/(?P<receiver>\w+)/$',  views.makefriend, name='make_friend'),
    url(r'^user/friend/(?P<pk>\d+)/(?P<flag>\d+)/$',  views.friendagree, name='friend_agree'),  # pk为对方用户id
    url(r'^user/notices/$', views.shownotice, name='show_notice'),
    url(r'^user/notices/(?P<pk>\d+)/$', views.noticedetail, name='notice_detail'),
    url(r'^user/messagedetail/(?P<pk>\d+)/$', MessageDetail.as_view(), name='message_detail'),  # pk为消息id
    url(r'^user/message/sendto/(?P<pk>\d+)/$', MessageCreate.as_view(), name='send_message'),  # pk为对方用户id
    url(r'^verify_code/$', views.verify_code,name='verify_code'),  # 配置验证码图片
    url(r'^show_verify2/$', views.show_verify2),  # 显示验证码界面
    url(r'^verify_check2/$', views.verify_check2, name='verify_check2'),  # 检测验证码
    url(r'^good/(?P<article_id>\d+)/(?P<user_id>\d+)$', views.good),
    url(r'^likes/', include('likes.urls')),
    url(r'^qwo/$', views.qwo, name='contact_us'),
    url(r'^form/', views.get_content),
]

rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views

template_name = {'template_name': 'rest_framework/login.html'}

app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

ourforum/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _#国际化支持
# from django.conf import settings
from ourforum_site.settings  import base as settings
from easy_thumbnails.fields import ThumbnailerImageField
from easy_thumbnails.files import get_thumbnailer
from el_pagination import settings as elp_setttings
from django.utils.encoding import python_2_unicode_compatible

from lbattachment.models import LBAttachment
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100)
    descn = models.TextField(blank=True)

    oid = models.PositiveIntegerField(default=999)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = 'category'
        verbose_name = _(u"Category")
        verbose_name_plural = _(u"Categories")
        ordering = ('-oid', 'created_on')

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Forum(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=110)
    description = models.TextField(default='')
    oid = models.PositiveIntegerField(default=999)
    category = models.ForeignKey(Category,verbose_name=u"Category")
    admins = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    num_topics = models.IntegerField(default=0)
    num_posts = models.IntegerField(default=0)

    last_post = models.ForeignKey(
        'Post', models.SET_NULL,
        verbose_name=_('Last post'),
        blank=True, null=True)

    class Meta:
        verbose_name = _(u"Forum")
        verbose_name_plural = _(u"Forums")
        ordering = ('oid', '-created_on')
        permissions = (
            ("sft_mgr_forum", _("Forum-Administrator")),
        )

    def __str__(self):
        return self.name

    def _count_nums_topic(self):
        return self.topic_set.all().count()

    def _count_nums_post(self):
        return Post.objects.filter(topic__forum=self).count()

    @models.permalink
    def get_absolute_url(self):
        return ('lbforum_forum', (), {'forum_slug': self.slug})

    def update_state_info(self, last_post=None, commit=True):
        self.num_topics = self._count_nums_topic()
        self.num_posts = self._count_nums_post()
        if not last_post:
            last_post = Post.objects.filter(
                topic__forum=self).order_by('-created_on').first()
        self.last_post = last_post
        if commit:
            self.save()

    def is_admin(self, user):
        if user.has_perm('ourforum.sft_mgr_forum'):
            return True
        return self.admins.filter(pk=user.pk).exists()


@python_2_unicode_compatible
class TopicType(models.Model):
    forum = models.ForeignKey(Forum, verbose_name=_(u'Forum'))
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    description = models.TextField(blank=True)
    class Meta:
        verbose_name = _(u"TopicType")
        verbose_name_plural = _(u"TopicTypes")
    def __str__(self):
        return self.name

LEVEL_CHOICES = (
    (30, _('Default')),
    (60, _('Distillate')),
)


@python_2_unicode_compatible
class Topic(models.Model):
    forum = models.ForeignKey(Forum, verbose_name=_(u'Forum'))
    topic_type = models.ForeignKey(
        TopicType, verbose_name=_(u'TopicType'),
        blank=True, null=True)
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    post = models.ForeignKey(
        'Post', verbose_name=_('Post'),
        related_name='topics', blank=True, null=True)
    subject = models.CharField(max_length=999)

    num_views = models.IntegerField(default=0)
    num_replies = models.PositiveSmallIntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    last_reply_on = models.DateTimeField(auto_now_add=True)
    last_post = models.ForeignKey(
        'Post', models.SET_NULL,
        verbose_name=_('Last post'),
        related_name='last_post_topics', blank=True, null=True)

    has_imgs = models.BooleanField(default=False)
    has_attachments = models.BooleanField(default=False)
    need_replay = models.BooleanField(default=False)  # need_reply :-)
    need_reply_attachments = models.BooleanField(default=False)

    closed = models.BooleanField(default=False)
    sticky = models.BooleanField(default=False)
    hidden = models.BooleanField(default=False)
    level = models.SmallIntegerField(choices=LEVEL_CHOICES, default=30)

    class Meta:
        ordering = ('-last_reply_on',)  # '-sticky'
        get_latest_by = ('created_on')
        verbose_name = 'Topic'
        verbose_name_plural = 'Topics'

    def __str__(self):
        return self.subject

    def _count_nums_replies(self):
        return self.posts.filter(topic_post=False).count()

    @models.permalink
    def get_absolute_url(self):
        return ('lbforum_topic', (), {'topic_id': self.id})

    def has_replied(self, user):
        if user.is_anonymous():
            return False
        return Post.objects.filter(posted_by=user, topic=self).count()

    def update_state_info(self, last_post=None, commit=True):
        self.num_replies = self._count_nums_replies()
        if not last_post:
            last_post = self.posts.order_by('-created_on').first()
        self.last_post = last_post
        if commit:
            self.save()

class Up(models.Model):
    """
    记录赞表
    """

    post = models.ForeignKey(verbose_name='发言', to='Topic', to_field='id', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='赞用户', to='LoginUser', to_field='id', on_delete=models.CASCADE)
    up = models.BooleanField(verbose_name='是否赞')


@python_2_unicode_compatible
class Post(models.Model):
    FORMAT_CHOICES = (
        ('bbcode', _('BBCode')),
        ('markdown', _('Markdown')),
        ('html', _('Html')),
    )
    topic = models.ForeignKey(Topic, verbose_name=_(u'Topic'), related_name='posts')
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    poster_ip = models.GenericIPAddressField()
    topic_post = models.BooleanField(default=False)
    comment_parent = models.ForeignKey('self', blank=True, null=True, related_name='childcomment')
    format = models.CharField(max_length=20, default='bbcode', choices=FORMAT_CHOICES)
    message = models.TextField()
    attachments = models.ManyToManyField(LBAttachment, blank=True)

    has_imgs = models.BooleanField(default=False)
    has_attachments = models.BooleanField(default=False)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    last_updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='last_updated_by_posts',
        blank=True, null=True)

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ('-created_on',)
        get_latest_by = ('created_on', )

    def __str__(self):
        return self.message[:80]

    def subject(self):
        if self.topic_post:
            return _('Topic: %s') % self.topic.subject
        return _('Re: %s') % self.topic.subject

    def file_attachments(self):
        return self.attachments.filter(is_img=False)

    def img_attachments(self):
        return self.attachments.filter(is_img=True)

    def _update_attachments_flag(self):
        self.has_attachments = self.attachments.filter(is_img=False).exists()
        self.has_imgs = self.attachments.filter(is_img=True).exists()
        self.save()
        if self.topic_post:
            topic = self.topic
            topic.has_attachments = self.has_attachments
            topic.has_imgs = self.has_imgs
            topic.save()

    def update_attachments(self, attachment_ids):
        self.attachments = LBAttachment.objects.filter(pk__in=attachment_ids)
        self._update_attachments_flag()

    def description(self):
            return u'%s 回复了您的话题(%s) R:《%s》' % (self.posted_by, self.topic, self.message)

    @models.permalink
    def get_absolute_url(self):
        return ('lbforum_post', (), {'post_id': self.pk})

    def get_absolute_url_ext(self):
        topic = self.topic
        post_idx = topic.posts.filter(created_on__lte=self.created_on).count()
        page = (post_idx - 1) / elp_setttings.PER_PAGE + 1
        return '%s?page=%s#p%s' % (topic.get_absolute_url(), page, self.pk)


@python_2_unicode_compatible
class OurForumUserProfile(models.Model):
    SEX_CHOICES = (
        ('F', _('Female')),
        ('M', _('Male')),
    )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='lbforum_profile',
        verbose_name=_('User'))
    nickname = models.CharField(
        _("Nickname"), max_length=255, blank=False, default='')
    avatar = ThumbnailerImageField(_("Avatar"), upload_to='imgs/avatars', blank=True, null=True)
    bio = models.TextField(blank=True,max_length=255)
    birthday = models.DateField(verbose_name=u'生日', null=True, blank=True)

    sex = models.CharField(max_length=20, default='M', choices=SEX_CHOICES)
    class Meta:
        db_table = 'userprofile'
        verbose_name = _(u"UserProfile")
        verbose_name_plural = _(u"UserProfiles")
    def __str__(self):
        return self.nickname or self.user.username

    def get_total_topics(self):
        return self.user.topic_set.count()

    def get_total_posts(self):
        return self.user.post_set.count()

    def get_absolute_url(self):

ourforum/templates/ourforum/widgets/categories_and_forums.html
{% load i18n %}
<div class="box" id="forums-box">
  <div class="cell">
    <span class="fade">{% trans "Forums" %}</span>
  </div>
  <div class="inner">
    {% for category in categories %}
      <strong class="green">{{ category }}</strong><br/>
      {% for forum in category.forum_set.all %}
        <a class="item_node" href="{% url 'lbforum_forum' forum_slug=forum.slug %}"><span> {{forum}} </span></a>
      {% endfor %}
      <br/>
    {% endfor %}
  </div>
</div>

ourforum/templates/ourforum/widgets/cur_user_profile.html
{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}
{% load lbforum_widget_tags %}
{% load lbutils %}

{% if user.is_authenticated %}
  <div class="box">
    <div class="cell">
      <table cellpadding="0" cellspacing="0" border="0" width="100%">
        <tbody>
          <tr>
            <td width="48" valign="top">
              <a href="{% url 'lbforum_profile' user_id=user.pk %}">
                <img width="48px" height="48px" src="{{ user.lbforum_profile.get_avatar_url }}" alt=""/>
              </a>
            </td>
            <td width="10" valign="top"></td>
            <td width="auto" align="left">
              <span class="bigger"><a href="{% url 'lbforum_profile' user_id=user.pk %}">{{ user.lbforum_profile }}</a></span>
              <div class="sep5"></div>
              <span class="fade"></span>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="inner">
      <span class="fade">{% trans "Joined on" %}: <strong>{{user.date_joined|date:"Y-m-d"}}</strong></span>
    </div>
  </div>
{% else %}
  <div class="box">
    <div class="cell">
      <strong>{% get_setting "OURFORUM_TITLE" %}</strong>
      <div class="sep5"></div>
      <span class="fade">{% get_setting "OURFORUM_SUB_TITLE" %}</span>
    </div>
    <div class="inner">
      <div class="sep5"></div>
      <div align="center">
        <a href="{% get_setting 'SIGNUP_URL' %}" class="super normal button">{% trans "Sign Up" %}</a>
        <div class="sep5"></div>
        <div class="sep10"></div>
        OR <a href="{% get_setting 'LOGIN_URL' %}">{% trans "Login" %}</a>
      </div>
    </div>
  </div>
{% endif %}

ourforum/templates/ourforum/widgets/lbf_status.html
{% load i18n %}
<div class="box">
  <div class="cell">
    <span class="fade">{% trans "Forum Status" %}</span>
  </div>
  <div class="inner">
    <table cellpadding="3" cellspacing="0" border="0" width="100%">
      <tbody>
        <tr>
          <td align="right" width="60%"><span class="fade">{% trans "Total number of registered users" %}</span></td>
          <td align="left"><strong>{{ total_users }}</strong></td>
        </tr>
        <tr>
          <td align="right" width="60%"><span class="fade">{% trans "Total number of topics" %}</span></td>
          <td align="left"><strong>{{ total_topics }}</strong></td>
        </tr>
        <tr>
          <td align="right" width="60%"><span class="fade">{% trans "Total number of posts" %}</span></td>
          <td align="left"><strong>{{ total_posts }}</strong></td>
        </tr>
       <tr>
          <td align="right" width="60%"><span class="fade">{% trans "Last registered user" %}</span></td>
          <td align="left"><strong>{{ last_registered_user }}</strong></td>
        </tr>
      <tr>
          <td align="right" width="60%"><span class="fade">{% trans "Online user count" %}</span></td>
          <td align="left"><strong>{{online_ips_count}}</strong></td>
        </tr>
        <tr>
          <td align="right" width="60%"><span class="fade">{% trans "Today topic count" %}</span></td>
          <td align="left"><strong>{{today_topic_number}}</strong></td>
        </tr>
        <tr>
          <td align="right" width="60%"><span class="fade">{% trans "Yesterday topic count" %}</span></td>
          <td align="left"><strong>{{lastday_topic_number}}</strong></td>
        </tr>
        </tbody>
    </table>
  </div>
</div>