lbattachment/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url('^upload__/$', views.upload__, name='lbattachment_upload__'),
    url('^delete__/$', views.delete__, name='lbattachment_delete__'),
    url('^change_descn__/$', views.change_descn__, name='lbattachment_change_descn__'),
    url('^download/$', views.download, name='lbattachment_download'),
]

likes/urls.py
#coding:utf-8

"""
    likes app
"""
from django.conf.urls import include, url
from likes.views import *
#http://localhost:8000/likes/ + 
#在project的urls.py导入整个url配置
urlpatterns = [
    url(r'^likes_change$',likes_change,name='likes_change'),
    url(r'^likes_nums$',likes_nums,name='likes_nums'),
]

ourforum/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from rest_framework import routers

from ourforum import views, profileviews
from ourforum import api
from ourforum.views import *
router = routers.DefaultRouter()
router.register(r'topic', api.TopicViewSet)

forum_patterns = [
    url(r'^(?P<forum_slug>[\w-]+)/$', views.forum, name='lbforum_forum'),
    url(r'^(?P<forum_slug>[\w-]+)/(?P<topic_type>[\w-]+)/$',
        views.forum, name='lbforum_forum'),
    url(r'^(?P<forum_slug>[\w-]+)/(?P<topic_type>[\w-]+)/(?P<topic_type2>[\w-]+)/$',
        views.forum, name='lbforum_forum'),
]

topic_patterns = [
    url('^(?P<topic_id>\d+)/$', views.topic, name='lbforum_topic'),
    url('^(?P<topic_id>\d+)/delete/$', views.delete_topic,
        name='lbforum_delete_topic'),
    url('^(?P<topic_id>\d+)/toggle_topic_attr/(?P<attr>[\w-]+)/$',
        views.toggle_topic_attr,
        name='lbforum_toggle_topic_attr'),
    url('^new/$', views.new_post, name='lbforum_new_topic'),
    url('^new/(?P<forum_id>\d+)/$', views.new_post, name='lbforum_new_topic'),
]

post_patterns = [
    url('^(?P<post_id>\d+)/$', views.post, name='lbforum_post'),
    url('^(?P<post_id>\d+)/edit/$', views.edit_post, name='lbforum_post_edit'),
    url('^(?P<post_id>\d+)/delete/$', views.delete_post,
        name='lbforum_post_delete'),
]

profile_patterns = [
    url(r'^$', profileviews.profile,
        name='lbforum_profile'),
    url(r'^(?P<user_id>\d+)/$', profileviews.profile,
        name='lbforum_profile'),
    url('^(?P<user_id>\d+)/topics/$', profileviews.user_topics,
        name='lbforum_user_topics'),
    url('^(?P<user_id>\d+)/posts/$', profileviews.user_posts,
        name='lbforum_user_posts'),
    url(r'^change/$', profileviews.change_profile,
        name='lbforum_change_profile'),
]

urlpatterns = [
    url(r'^$', views.index, name='lbforum_index'),
    url(r'^recent/$', views.recent, name='lbforum_recent'),
    url(r'^forum/', include(forum_patterns)),
    url(r'^topic/', include(topic_patterns)),
    url(r'^profile/', include(profile_patterns)),
    url(r'^api/', include(router.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^i18n/setlang', views.set_language,name='selected_language'),
    url('^reply/new/(?P<topic_id>\d+)/$', views.new_post,
        name='lbforum_new_replay'),
    url(r'^post/', include(post_patterns)),
    url(r'^lang.js$', TemplateView.as_view(template_name='ourforum/lang.js'),
        name='lbforum_lang_js'),
    url('^markitup_preview/$', views.markitup_preview,
        name='markitup_preview'),
    url(r'^makefriend/(?P<sender>\w+)/(?P<receiver>\w+)/$',  views.makefriend, name='make_friend'),
    url(r'^user/friend/(?P<pk>\d+)/(?P<flag>\d+)/$',  views.friendagree, name='friend_agree'),  # pk为对方用户id
    url(r'^user/notices/$', views.shownotice, name='show_notice'),
    url(r'^user/notices/(?P<pk>\d+)/$', views.noticedetail, name='notice_detail'),
    url(r'^user/messagedetail/(?P<pk>\d+)/$', MessageDetail.as_view(), name='message_detail'),  # pk为消息id
    url(r'^user/message/sendto/(?P<pk>\d+)/$', MessageCreate.as_view(), name='send_message'),  # pk为对方用户id
    url(r'^verify_code/$', views.verify_code,name='verify_code'),  # 配置验证码图片
    url(r'^show_verify2/$', views.show_verify2),  # 显示验证码界面
    url(r'^verify_check2/$', views.verify_check2, name='verify_check2'),  # 检测验证码
    url(r'^good/(?P<article_id>\d+)/(?P<user_id>\d+)$', views.good),
    url(r'^likes/', include('likes.urls')),
    url(r'^qwo/$', views.qwo, name='contact_us'),
    url(r'^form/', views.get_content),
]

rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views

template_name = {'template_name': 'rest_framework/login.html'}

app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

ourforum/models.py
# -*- coding: UTF-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.utils.translation import ugettext_lazy as _#国际化支持
# from django.conf import settings
from ourforum_site.settings  import base as settings
from easy_thumbnails.fields import ThumbnailerImageField
from easy_thumbnails.files import get_thumbnailer
from el_pagination import settings as elp_setttings
from django.utils.encoding import python_2_unicode_compatible

from lbattachment.models import LBAttachment
from django.contrib.auth.models import AbstractUser
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
@python_2_unicode_compatible
class Category(models.Model):
    name = models.CharField(max_length=100)
    descn = models.TextField(blank=True)

    oid = models.PositiveIntegerField(default=999)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)

    class Meta:
        db_table = 'category'
        verbose_name = _(u"Category")
        verbose_name_plural = _(u"Categories")
        ordering = ('-oid', 'created_on')

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class Forum(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=110)
    description = models.TextField(default='')
    oid = models.PositiveIntegerField(default=999)
    category = models.ForeignKey(Category,verbose_name=u"Category")
    admins = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    num_topics = models.IntegerField(default=0)
    num_posts = models.IntegerField(default=0)

    last_post = models.ForeignKey(
        'Post', models.SET_NULL,
        verbose_name=_('Last post'),
        blank=True, null=True)

    class Meta:
        verbose_name = _(u"Forum")
        verbose_name_plural = _(u"Forums")
        ordering = ('oid', '-created_on')
        permissions = (
            ("sft_mgr_forum", _("Forum-Administrator")),
        )

    def __str__(self):
        return self.name

    def _count_nums_topic(self):
        return self.topic_set.all().count()

    def _count_nums_post(self):
        return Post.objects.filter(topic__forum=self).count()

    @models.permalink
    def get_absolute_url(self):
        return ('lbforum_forum', (), {'forum_slug': self.slug})

    def update_state_info(self, last_post=None, commit=True):
        self.num_topics = self._count_nums_topic()
        self.num_posts = self._count_nums_post()
        if not last_post:
            last_post = Post.objects.filter(
                topic__forum=self).order_by('-created_on').first()
        self.last_post = last_post
        if commit:
            self.save()

    def is_admin(self, user):
        if user.has_perm('ourforum.sft_mgr_forum'):
            return True
        return self.admins.filter(pk=user.pk).exists()


@python_2_unicode_compatible
class TopicType(models.Model):
    forum = models.ForeignKey(Forum, verbose_name=_(u'Forum'))
    name = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100)
    description = models.TextField(blank=True)
    class Meta:
        verbose_name = _(u"TopicType")
        verbose_name_plural = _(u"TopicTypes")
    def __str__(self):
        return self.name

LEVEL_CHOICES = (
    (30, _('Default')),
    (60, _('Distillate')),
)


@python_2_unicode_compatible
class Topic(models.Model):
    forum = models.ForeignKey(Forum, verbose_name=_(u'Forum'))
    topic_type = models.ForeignKey(
        TopicType, verbose_name=_(u'TopicType'),
        blank=True, null=True)
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    post = models.ForeignKey(
        'Post', verbose_name=_('Post'),
        related_name='topics', blank=True, null=True)
    subject = models.CharField(max_length=999)

    num_views = models.IntegerField(default=0)
    num_replies = models.PositiveSmallIntegerField(default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    last_reply_on = models.DateTimeField(auto_now_add=True)
    last_post = models.ForeignKey(
        'Post', models.SET_NULL,
        verbose_name=_('Last post'),
        related_name='last_post_topics', blank=True, null=True)

    has_imgs = models.BooleanField(default=False)
    has_attachments = models.BooleanField(default=False)
    need_replay = models.BooleanField(default=False)  # need_reply :-)
    need_reply_attachments = models.BooleanField(default=False)

    closed = models.BooleanField(default=False)
    sticky = models.BooleanField(default=False)
    hidden = models.BooleanField(default=False)
    level = models.SmallIntegerField(choices=LEVEL_CHOICES, default=30)

    class Meta:
        ordering = ('-last_reply_on',)  # '-sticky'
        get_latest_by = ('created_on')
        verbose_name = 'Topic'
        verbose_name_plural = 'Topics'

    def __str__(self):
        return self.subject

    def _count_nums_replies(self):
        return self.posts.filter(topic_post=False).count()

    @models.permalink
    def get_absolute_url(self):
        return ('lbforum_topic', (), {'topic_id': self.id})

    def has_replied(self, user):
        if user.is_anonymous():
            return False
        return Post.objects.filter(posted_by=user, topic=self).count()

    def update_state_info(self, last_post=None, commit=True):
        self.num_replies = self._count_nums_replies()
        if not last_post:
            last_post = self.posts.order_by('-created_on').first()
        self.last_post = last_post
        if commit:
            self.save()

class Up(models.Model):
    """
    记录赞表
    """

    post = models.ForeignKey(verbose_name='发言', to='Topic', to_field='id', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='赞用户', to='LoginUser', to_field='id', on_delete=models.CASCADE)
    up = models.BooleanField(verbose_name='是否赞')


@python_2_unicode_compatible
class Post(models.Model):
    FORMAT_CHOICES = (
        ('bbcode', _('BBCode')),
        ('markdown', _('Markdown')),
        ('html', _('Html')),
    )
    topic = models.ForeignKey(Topic, verbose_name=_(u'Topic'), related_name='posts')
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL)
    poster_ip = models.GenericIPAddressField()
    topic_post = models.BooleanField(default=False)
    comment_parent = models.ForeignKey('self', blank=True, null=True, related_name='childcomment')
    format = models.CharField(max_length=20, default='bbcode', choices=FORMAT_CHOICES)
    message = models.TextField()
    attachments = models.ManyToManyField(LBAttachment, blank=True)

    has_imgs = models.BooleanField(default=False)
    has_attachments = models.BooleanField(default=False)

    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(blank=True, null=True)
    last_updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='last_updated_by_posts',
        blank=True, null=True)

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ('-created_on',)
        get_latest_by = ('created_on', )

    def __str__(self):
        return self.message[:80]

    def subject(self):
        if self.topic_post:
            return _('Topic: %s') % self.topic.subject
        return _('Re: %s') % self.topic.subject

    def file_attachments(self):
        return self.attachments.filter(is_img=False)

    def img_attachments(self):
        return self.attachments.filter(is_img=True)

    def _update_attachments_flag(self):
        self.has_attachments = self.attachments.filter(is_img=False).exists()
        self.has_imgs = self.attachments.filter(is_img=True).exists()
        self.save()
        if self.topic_post:
            topic = self.topic
            topic.has_attachments = self.has_attachments
            topic.has_imgs = self.has_imgs
            topic.save()

    def update_attachments(self, attachment_ids):
        self.attachments = LBAttachment.objects.filter(pk__in=attachment_ids)
        self._update_attachments_flag()

    def description(self):
            return u'%s 回复了您的话题(%s) R:《%s》' % (self.posted_by, self.topic, self.message)

    @models.permalink
    def get_absolute_url(self):
        return ('lbforum_post', (), {'post_id': self.pk})

    def get_absolute_url_ext(self):
        topic = self.topic
        post_idx = topic.posts.filter(created_on__lte=self.created_on).count()
        page = (post_idx - 1) / elp_setttings.PER_PAGE + 1
        return '%s?page=%s#p%s' % (topic.get_absolute_url(), page, self.pk)


@python_2_unicode_compatible
class OurForumUserProfile(models.Model):
    SEX_CHOICES = (
        ('F', _('Female')),
        ('M', _('Male')),
    )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, related_name='lbforum_profile',
        verbose_name=_('User'))
    nickname = models.CharField(
        _("Nickname"), max_length=255, blank=False, default='')
    avatar = ThumbnailerImageField(_("Avatar"), upload_to='imgs/avatars', blank=True, null=True)
    bio = models.TextField(blank=True,max_length=255)
    birthday = models.DateField(verbose_name=u'生日', null=True, blank=True)

    sex = models.CharField(max_length=20, default='M', choices=SEX_CHOICES)
    class Meta:
        db_table = 'userprofile'
        verbose_name = _(u"UserProfile")
        verbose_name_plural = _(u"UserProfiles")
    def __str__(self):
        return self.nickname or self.user.username

    def get_total_topics(self):
        return self.user.topic_set.count()

    def get_total_posts(self):
        return self.user.post_set.count()

    def get_absolute_url(self):

ourforum/templates/ourforum/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

{% load lbutils %}

{% block html_declare %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="{{ LANGUAGE_CODE }}" xml:lang="{{ LANGUAGE_CODE }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}/>
{% endblock %}
  <head>
     <link rel="shortcut icon" href="/static/admin/img/favicon.ico">
<link rel="stylesheet" href="/static/ourforum/styles/v2ex/default.css"/>
    <!--<link rel="bookmark"  type="image/x-icon"  href="./imgs/favicon.ico"/>-->


    <title>
      {% get_setting "OURFORUM_TITLE" %}
      -
      {% get_setting "OURFORUM_SUB_TITLE" %}
    </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    {% include 'ourforum/inc_styles.html' %}
    {% block extra_header %}{% endblock %}
  </head>

  <body>

    {% block content %} {% endblock %}
    {% block footer_js %} {% endblock %}
  <!--回到顶部-->
   <!--<div id="back-to-top" class="red" data-scroll="body" style="top:-46px;color:red;">回到顶部 </div>-->
      <!--<script src="jquery-1.12.4.js"></script>-->
  <!--<script type="text/javascript" src="home.js"></script>-->
  </body>
</html>

ourforum/templates/ourforum/base_site.html
{% extends 'ourforum/base.html' %}

{% load lbutils %}
{% load i18n %}

{% block title %}
  {% get_setting "OURFORUM_TITLE" %}
{% endblock %}

{% block content %}
  {% include 'ourforum/inc_header.html' %}

  <div id="Wrapper">
    <div id="Main">
      <div id="Sidebar">
      </div>

      <div id="Rightbar">
        {% block content_right_bar%}
        {% endblock %}
      </div>

      <div id="Content">
        {% block content_content %}
        {% endblock %}
      </div>

      <div class="c">
      </div>
    </div>
  </div>

  {% include 'ourforum/plugins/inc_footer.html'%}
{% endblock %}
 <script type="text/javascript"  src="/static/ourforum/js/footer.js">

    </script>


<link rel="stylesheet" type="text/css" href="/static/ourforum/styles/v2ex/default.css" />

ourforum/templates/ourforum/forum.html
{% extends "ourforum/base_site.html" %}

{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}
{% load lbutils %}
{% load lbforum_widget_tags %}
{% load el_pagination_tags %}

{% block title %}

  {{ forum }} - {% get_setting "OURFORUM_TITLE" %}
{% endblock %}

{% block content_right_bar %}

  {% if forum.description %}
    <div class="box">
      <div class="cell">
        <span class="fade">{% trans "Forum Description" %}</span>
      </div>
      <div class="inner">
        {{forum.description|bbcode|safe}}
      </div>
    </div>
    <div class="sep20"></div>
  {% endif %}

  {% if forum.admins.all.count %}
    <div class="box">
      <div class="cell">
        <span class="fade">{% trans "Forum Admin" %}</span>
      </div>
      <div class="inner">
        {% for o in forum.admins.all %}
          <a class="item_node" href="{% url 'lbforum_profile' o.pk %}">
            <span> {{ o.lbforum_profile }} </span>
          </a>
        {% endfor %}
      </div>
    </div>
    <div class="sep20"></div>
  {% endif %}

    {% lbf_categories_and_forums %}
    <div class="sep20"></div>

    {% if forum.topictype_set.all.count %}
      <div class="box">
        <div class="cell">
          <span class="fade">{% trans "Topic Type" %}</span>
        </div>
        <div class="inner">
          <a class="item_node {% if not topic_type2 %}selected{% endif %}" 
              href="{% forum_url forum topic_type '' %}">
            <span> {% trans "All" %} </span>
          </a>
          {% for tp in forum.topictype_set.all %}
            <a class="item_node {% if topic_type2 == tp.slug %}selected{% endif %}" 
                href="{% forum_url forum topic_type tp.slug %}">
              <span> {{ tp }} </span>
            </a>
          {% endfor %}
        </div>
      </div>
    {% endif %}
{% endblock %}

{% block content_content %}
  {% paginate topics %}
  {% get_pages %}
  <div class="box">
    <div class="cell" style="padding-bottom: 0px;">
      <table cellpadding="0" cellspacing="0" border="0" width="100%">
        <tr>
          <td width="auto" valign="top">
            <div class="fr" align="right">
              <span class="snow">
                {% trans "Topics" %}
                <strong>
                  [ {% page_range_info pages %} ]
                </strong>
              </span>
            </div>
            <span class="bigger">
              <a href="{% url 'lbforum_index' %}">{% trans "Home" %}</a>
              <span class="chevron">&raquo;</span>
              {{ forum }}
            </span>
            <div class="sep10"></div>
            <div class="sep10"></div>
            <div align="left">
              <a href="{% url 'lbforum_new_topic' forum_id=forum.pk %}" class="super normal button">{% trans "Post new topic" %}</a>
            </div>
            <div class="sep5"></div>
            <div class="sep10"></div>
            <div>
              <div class="tp-btn {% if topic_type != 'good' %}selected{% endif %}">
                <a href="{% forum_url forum '' topic_type2 %}">{% trans "All" %}</a>
              </div>
              <div class="tp-btn {% if topic_type == 'good' %}selected{% endif %}">
                <a href="{% forum_url forum 'good' topic_type2 %}">{% trans "Distillate District" %}</a>
              </div>
            </div>
          </td>
        </tr>
      </table>
    </div>
    {% include 'ourforum/inc_topic_list.html' %}
    <div class="inner">
      {% show_pages %}
    </div>
  </div>
{% endblock %}

ourforum/templates/ourforum/inc_header.html
{% load i18n %}
{% load lbutils %}

<link rel="stylesheet" type="text/css" href="/static/ourforum/styles/v2ex/default.css">
<script type="text/javascript" src="/static/ourforum/js/jquery-1.11.3.min.js">
function myrefresh() {
    window.location.reload();
}
setTimeout('myrefresh()', 1000); //指定1秒刷新一次
</script>

<div id="Top">
  <div id="TopMain">
    <p id="title"><a href="{% url 'lbforum_index' %}">{% get_setting "OURFORUM_TITLE" %}</a></p>
    <div id="Navigation">
      <ul>
        {% include 'ourforum/plugins/inc_header_left_links.html' %}
        {% if user.is_authenticated %}
          <br>
          <li id="mn_portal"><a href="{% url 'show_notice' %}" hidefocus="true" >{{user.username}}({%if message_number %}{{message_number}}{%else%}0{%endif%})</a></li>
          <li id="navprofile"><a href="{% url 'lbforum_profile' %}">{% trans "My profile" %}</a></li>
          <li id="navlogout"><a href="{% get_setting 'LOGOUT_URL' %}?next={% url 'lbforum_index' %}">{% trans "Logout" %}</a></li>

          {% else %}
          <li id="navregister"><a href="{% get_setting 'SIGNUP_URL' %}">{% trans "Sign Up" %}</a></li>
          <li id="navlogin"><a href="{% get_setting 'LOGIN_URL' %}">{% trans "Login" %}</a></li>
           <!--<li id="navqwo"><a href="{% url 'contact_us'%}">{% trans "Contact Us" %}</a></li>-->
        {% endif %}
      </ul>
    </div>
    <div id="Search">
      <form action="{% url 'lbforum_recent' %}">
        <input type="text" class="search" maxlength="40" name="q" value="" id="q" placeholder="Search here..." required>
          <select name="cars">
<option >Yahoo</option>
<option value="fiat" selected="selected">Recent</option>
<option value="audi">Zhihu</option>
</select>

        <input type="submit" class="super normal button" value="{% trans 'Search' %}" style="-moz-border-radius: 0px 5px 5px 0px; border: none;">

      </form>
<form action="{% url 'selected_language' %}" method="post">
    {% csrf_token %}
    <input name="next" type="hidden" value="{{lbforum_index}}"/>
    <select name="language"> {% for lang in LANGUAGES %}
        <option value="{{ lang.0 }}">{{ lang.1 }}
        </option>
        {% endfor %} </select>
    <input type="submit" value="Go" />
</form>
    </div>

  </div>
</div>

ourforum/templates/ourforum/inc_post_content.html
{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}

{% if not post.topic_post or not post.topic.need_reply or has_replied %}
  <p>{% bbcode post.message has_replied %}</p>
  {% if post.edited_by %}
    <p class="postedit"><em>{% trans "Last edit by" %} {{post.edited_by}} ({{ post.updated_on|lbtimesince }})</em></p>
  {% endif %}
  {% if post.has_attachments %}
    <div class="entry-attachments">
      <b>{% trans "Attachments" %}:</b>
      <ul>
        {% for attachment in post.file_attachments %}
          <li>
            {% show_attach attachment post has_replied hide_attachs %}
            <span>{{ attachment.description }}</span>
          </li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}
  {% if post.has_imgs %}
    <div class="entry-attachments-img-s" id="entry-attachments-img-s{{ post.id }}">
      <a href="#"><b>{% trans "Show Image Attachments" %}</b></a>
    </div>
    <div class="entry-attachments-img" id="entry-attachments-img-{{ post.id }}">
      <b>{% trans "Image Attachments" %}:</b>
      <ul>
        {% for attachment in post.img_attachments %}
          <li>
            {% show_attach attachment post has_replied hide_attachs %}
            <span>{{ attachment.description }}</span>
          </li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}
{% else %}
  <span class="need-reply">{% trans "to see the content, user must reply first." %}</span>
{% endif %}

ourforum/templates/ourforum/inc_styles.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" media="screen" href="{% static 'ourforum/styles/v2ex/default.css' %}"/>
   <script src="/static/ourforum/js/jquery-1.12.4.js"></script>
   <script type="text/javascript">
       window.onload = function () {
           // 利用 data-scroll 属性，滚动到任意 dom 元素
           $.scrollto = function (scrolldom, scrolltime) {
               $(scrolldom).click(function () {
                   var scrolltodom = $(this).attr("data-scroll");
                   $(this).addClass("active").siblings().removeClass("active");
                   $('html, body').animate({
                       scrollTop: $(scrolltodom).offset().top
                   }, scrolltime);
                   return false;
               });
           };
           //判断位置控制 返回顶部的显隐
           if ($(window).width() > 800) {//如果窗体的宽度大于800
               var backTo = $("#back-to-top");//获取back-to-top对象
               var backHeight = $(window).height() - 980 + 'px';//让window高度减980
               $(window).scroll(function () {
                   if ($(window).scrollTop() > 700 && backTo.css('top') === '-900px') {
                       backTo.css('top', backHeight);
                   }
                   else if ($(window).scrollTop() <= 700 && backTo.css('top') !== '-900px') {
                       backTo.css('top', '-900px');
                   }
               });

           }
           //启用
           $.scrollto("#back-to-top", 800);

       }
   </script>

ourforum/templates/ourforum/inc_topic_list.html
{% for t in topics %}     
{% include 'ourforum/inc_topic_detail.html' %}
{% endfor %}

ourforum/templates/ourforum/message.html
{% extends 'ourforum/profile/base.html' %}

{% load i18n %}
{% load lbforum_filters %}
{% load lbforum_tags %}

{% block content_content %}
<div class="box">
  <!--<div class="inner">-->
     <table cellspacing="0" cellpadding="5" border="0">
      <tbody>
发送者:{{ message.sender }}<br>
内容:{{ message.content }}<br>
时间:{{ message.created_on|date:"Y-m-d H:i:s" }}
<br>
<br>

<a href="{% url 'send_message' message.sender.id %}">回复消息</a>
  </tbody>
    </table>
     </div>
{% endblock %}